spring:
  security:
    oauth2:
      client:
        registration:
          google :
            clientId: 311671349138-58t53qman629a2nu33tst3f9urq1r8c5.apps.googleusercontent.com
            clientSecret: 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

